name = "roo-code-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "development"

[env.production]
name = "roo-code-api-prod"

[env.production.vars]
ENVIRONMENT = "production"
OAUTH_CLIENT_ID = "Y614615879012-qn152568j0bmlg7cif4fvfcfdmrbd23f.apps.googleusercontent.com"
OAUTH_CLIENT_SECRET = "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"
JWT_SECRET = "lkjilokolkjiuhygftrderfgtyhjunbv"

[[env.production.d1_databases]]
binding = "DB"
database_name = "roo-code-users"
database_id = "e0953fc3-7810-42bc-aa4f-c0b17f44d192"